- name: ensure influxdb installed
  shell: which influxd
  args: 
    executable: /bin/bash
  register: influxdb_installed
  ignore_errors: True

- block:
  - name: Copy Influxdb deb
    copy: src=influxdb_1.7.8_amd64.deb  dest=/tmp
  
  - name: dpkg install influxdb
    shell: dpkg -i /tmp/influxdb_1.7.8_amd64.deb
 
  - name: mkdir /data/apm
    file: path=/data/apm state=directory recurse=yes

  - name: mkdir mod
    file: path=/data/apm/influxdb/{{ item }} state=directory recurse=yes  owner=influxdb group=influxdb 
    with_items:
      - meta
      - data
      - wal
  
  - name: configuration file
    template: src=influxdb.conf.j2  dest=/etc/influxdb/influxdb.conf

  - name: configuration file change owner
    file: path=/etc/influxdb/influxdb.conf owner=influxdb group=influxdb
  
  - name: restart influxdb
    systemd: state=started name=influxdb
  
  - name: init script
    script: init.sh
  
  when: influxdb_installed.stdout.find('influxd') == -1
